### ISSUE TITLE
FEVER and WebShop code

### ISSUE THREAD

**Issue by TianHongZXY** [ysymyth/ReAct#1]
Hello @ysymyth, thanks for sharing your code, excellent work! Is there any plan to release the code of FEVER and WebShop? Thank you!

**Comment by ysymyth** [comment]
Thanks for asking, plan to do it this month!

**Comment by ysymyth** [comment]
Hi, these two have been added. WebShop is a bit of a workaround as it scrapes the live site instead of using https://github.com/princeton-nlp/WebShop, but is usable. I'll close it for now and feel free to open new questions!
