### ISSUE TITLE
Could you please tell me how to access the url in the WebShop.ipynb: http://3.83.245.205:3000 ?

### ISSUE THREAD

**Issue by junleiz** [ysymyth/ReAct#15]
Thank you for your code. But I can not access the webshop url in your jupterbook. Do I have to launch another servise?

**Comment by ysymyth** [comment]
we are trying to set it up soon. meanwhile, maybe use native webshop env instead? https://github.com/princeton-nlp/WebShop

**Comment by junleiz** [comment]
Thank you for your reply! Could you please tell me whether you use the all the data in your env?

I have set up an webshop env using under the:
```
DEFAULT_ATTR_PATH = join(BASE_DIR, '../data/items_ins_v2_1000.json')
DEFAULT_FILE_PATH = join(BASE_DIR, '../data/items_shuffle_1000.json')
``
But it raises the out of index error. 
I have changed it to the following setting, but the server do not response.
```
DEFAULT_ATTR_PATH = join(BASE_DIR, '../data/items_ins_v2.json')
DEFAULT_FILE_PATH = join(BASE_DIR, '../data/items_shuffle.json')
```

**Comment by ysymyth** [comment]
I think you should use 
```DEFAULT_ATTR_PATH = join(BASE_DIR, '../data/items_ins_v2.json')
DEFAULT_FILE_PATH = join(BASE_DIR, '../data/items_shuffle.json')```

when you say it does not respond, what command did you run? when you ctrl+c where is it stuck?

**Comment by ysymyth** [comment]
Closing for now and feel free to open new ones!
