### ISSUE TITLE
Could you provide text-davinci-002 log on HotpotQA 500 (30.8EM)?

### ISSUE THREAD

**Issue by GitYiheng** [ysymyth/ReAct#17]
Hi Shunyu,

Could you provide text-davinci-002 trajectory on HotpotQA 500 (30.8EM in Table 5 of A.1 GPT-3 Experiments)? 

Thank you!

**Comment by UhnTiss** [comment]
I would also be interested in that. Best regards!

**Comment by ysymyth** [comment]
hi check https://github.com/ysymyth/ReAct/issues/9 --- sorry text-davinci-002 traj might be hard to find now...
