### ISSUE TITLE
Webshop experiment details for numbers in paper

### ISSUE THREAD

**Issue by sgdgp** [ysymyth/ReAct#20]
Hi,

For webshop env, what was the number of retrieved items displayed per page?
As per the code, it seems item names indexed after 3 are purposefully omitted, which does not seem to be clarified in the actual paper.

Could you please explicitly clarify this setting just so that I am clear whether this was a small change for visualization in code or was it done for all results reported in the paper?

I was looking through the earlier issues in the repo and couldn't find this resolved in the closed issues.

Thanks!

**Comment by ysymyth** [comment]
Hi @sgdgp thanks for the great question! We only used first 3 items due to context limit at the same --- you can check the prompt and trajectory in our appendix to confirm this!
