### ISSUE TITLE
WEBSHOP_URL = "http://3.83.245.205:3000" 遇到一些问题

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [ysymyth/ReAct#23]
请问一下，在webshop实验中
我们的网页地址是： WEBSHOP_URL = "http://3.83.245.205:3000"
请问我应该如何把这个网页替换为我自己的网页？有网页构建的代码吗

**Comment by ysymyth** [comment]
the live site is down for now. you can follow https://github.com/princeton-nlp/WebShop and create a localhost port, or use the python package directly. let me know if you run into issues, and happy to pull request if you make it work!

**Comment by xiaxiaxiatengxi** [comment]
谢谢您的回复！

**Comment by GaoDalie** [comment]
I have the Same issues I want run the code , but I got invalid observation 
Please could I use any url into your code or I need to build my own webshop url @ysymyth

**Comment by ysymyth** [comment]
the website is down due to cost issues, so you need to follow https://github.com/princeton-nlp/WebShop and create a localhost port
