### ISSUE TITLE
question on alfworld and textworld version.

### ISSUE THREAD

**Issue by WZX0Swarm0Robotics** [ysymyth/ReAct#30]
when i run alfworld.ipynb, it return:
Initializing AlfredTWEnv...
Checking for solvable games...
Overall we have 134 games
Evaluating with 134 games
Traceback (most recent call last):
  File "/home/ict/ReAct/react.py", line 55, in <module>
    env = env.init_env(batch_size=1)
  File "/home/ict/miniconda3/envs/react1/lib/python3.9/site-packages/alfworld/agents/environment/alfred_tw_env.py", line 224, in init_env
    infos = textworld.EnvInfos(won=True, admissible_commands=True, expert_type=expert_type, expert_plan=expert_plan, extras=["gamefile"])
  File "/home/ict/miniconda3/envs/react1/lib/python3.9/site-packages/textworld/core.py", line 109, in __init__
    raise ValueError(msg)
ValueError: Unknown information requested: ['expert_plan', 'expert_type']. Available information are: ['admissible_commands', 'command_templates', 'description', 'entities', 'extras', 'facts', 'fail_facts', 'feedback', 'game', 'intermediate_reward', 'inventory', 'last_action', 'last_command', 'location', 'lost', 'max_score', 'moves', 'objective', 'policy_commands', 'score', 'verbs', 'win_facts', 'won']
 it seems that textworld do not work any more.

**Comment by ai-nikolai** [comment]
@WZX0Swarm0Robotics what are your version numbers?

**Comment by ai-nikolai** [comment]
The following seems to work for me:
```
alfworld==0.3.2
fast-downward-textworld==20.6.1
textworld==1.6.1
```

**Comment by ysymyth** [comment]
nice!
