### ISSUE TITLE
Have you considered renaming this project?

### ISSUE THREAD

**Issue by danmarshall** [ysymyth/ReAct#4]
Hello, thank you for this important work and project!
I'm already seeing many references to the paradigm. The problem is that there was already a massively popular project named React. This makes searches for ReAct somewhat difficult.

**Comment by ysymyth** [comment]
thanks for the tip! would ReAct-llm-prompting be better?

**Comment by danmarshall** [comment]
🤷🏽‍♂️ Maybe only front-end devs like me are confused 😁
