### ISSUE TITLE
the power of reason & action pattern has been proved in autogpt 

### ISSUE THREAD

**Issue by VinciLee1** [ysymyth/ReAct#5]
I was wondering if autogpt is inspired by your ideas. anyway, thanks for your great efforts.

**Comment by ysymyth** [comment]
our work came long (in ai standard haha) before autogpt, and they clearly use ReAct's "thought-action" patten (among some other great ideas). check out Jim Fan's tweet about this: https://twitter.com/DrJimFan/status/1647631172967464961
