### ISSUE TITLE
How can I install ReAct?

### ISSUE THREAD

**Issue by alxfed** [ysymyth/ReAct#6]
Don't give me links to Alfworld! The installations there don't work, the support is nonexistent.
How can I install ReAct on my Ubuntu 22.04?

**Comment by alxfed** [comment]
Got it. ReAct is no more.

**Comment by ysymyth** [comment]
Hi, README.md links to ALFWorld repo about how to install: https://github.com/alfworld/alfworld

Is there any concrete problem you faced during installing ALFWorld?
