### ISSUE TITLE
Jupyter output on HotpotQA

### ISSUE THREAD

**Issue by seahou3e** [ysymyth/ReAct#9]
@ysymyth Thanks for your good work!

Can you attach the output of HotpotQA ([hotpotqa.ipynb](https://github.com/ysymyth/ReAct/blob/master/hotpotqa.ipynb)), like those in ([FEVER.ipynb](https://github.com/ysymyth/ReAct/blob/master/FEVER.ipynb))? Thank you!

**Comment by ysymyth** [comment]
Hi, I don't have the davinci-002 trajectories at hand, but I think the following is the davinci-003 trajectories (35.4 EM):

https://gist.githubusercontent.com/ysymyth/3776303f2b40a760e61e45ea43cb3440/raw/52019ece175f2231f5f28aa9361d3aeecf361aba/hotpot_react_davinci-003.txt

I'll close it for now but feel free to open new issues!
